services:
  nacos:
    image: nacos/nacos-server:v2.4.2
    container_name: nacos-standalone
    env_file:
      - .env
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "18080:8080"
      - "18848:8848"
      - "19848:9848"
    networks:
      - wx

networks:
  wx:
    external: true